### ISSUE TITLE
Release new version

### ISSUE THREAD

**Issue by ofek** [google/go-replayers#27]
Hello! Is there any chance a new version of the tool `httpr` could be released soon with updated artifacts for each platform? We are in need of this but the latest release seems to have been 5 years ago https://github.com/googleapis/google-cloud-go/releases/tag/v0.25.0

cc @jba 🙂

**Comment by jba** [comment]
I just published a release a httpreplay/v1.2.0. Let me know if that works for you.

**Comment by ofek** [comment]
Thanks! Can you also publish a binary for each platform like before? That is what we'll ultimately use

**Comment by jba** [comment]
Oh, I see. I maintain this repo, google/go-replayers. The googleapis/google-cloud-go repo is maintained by others; you should comment on their issue tracker.

**Comment by ofek** [comment]
I opened https://github.com/googleapis/google-cloud-go/issues/7628
