### ISSUE TITLE
Binding to :<port> causing warning on macOS

### ISSUE THREAD

**Issue by andybons** [google/go-replayers#4]
👋 @jba,

[Binding to a port without a host](https://github.com/google/go-replayers/blob/master/httpreplay/internal/proxy/record.go#L140) will cause the following warning if the binary is not codesigned on macOS:

<img width="532" alt="Screen Shot 2020-04-30 at 6 01 21 PM" src="https://user-images.githubusercontent.com/365204/80764557-f4bc3700-8b0e-11ea-8810-8144eb69e09a.png">

I’m not certain whether it’s possible to specify the host anywhere, but it would be nice to not have the warning pop up in tests that are using this (anecdotally, clicking “Deny” has no negative effect on the test 🤷).

**Comment by jba** [comment]
I added `localhost` to the address. I can't imagine that would make a difference, but you could pull the latest commit (unversioned) and try it. I can't test on my Mac at the moment.

**Comment by jba** [comment]
Fixed by #5.
