### ISSUE TITLE
Troubleshooting "request not found" error

### ISSUE THREAD

**Issue by gmgchow** [google/go-replayers#6]
I followed the examples in the documentation and successfully recorded my grpc request. However, when I tried to replay the `.replay` file by sending the exact same request, I received a `replayer: request not found: message_id:"test" message_body:"test"` error. What is the best way to troubleshoot this, and how can I open the `.replay` file to check what was recorded?

**Comment by jba** [comment]
Unfortunately the file format is binary. It uses this protobuf: https://github.com/google/go-replayers/blob/master/grpcreplay/proto/grpcreplay/grpcreplay.proto. 

Can you post a reproduction of the problem here? I'll try to debug.

**Comment by jba** [comment]
To display the contents of the `.replay` file, use [Fprint](https://pkg.go.dev/github.com/google/go-replayers/grpcreplay?tab=doc#Fprint).

**Comment by gmgchow** [comment]
I tried debugging using Fprint and found that at [this line](https://github.com/google/go-replayers/blob/master/grpcreplay/grpcreplay.go#L564), both `e` and `err` are nil so the function exits. I am not sure why `e` is nil.

This is a sample of how I am trying to use this tool: https://play.golang.org/p/5nm9S3kjpaV . Basically if no `.replay` file is found, I want to create one so that the next time the same test is run, it will replay the traffic that was recorded.

**Comment by jba** [comment]
@gmgchow, `e` and `error` are nil at end of file. If all you see from Fprint is
```
initial state: ...
```
then you have no records in your replay file.

Are you checking the error returned from Fprint? Maybe there is some other problem.

Also, as @vangent mentioned, you need to handle the error when you close the file (after line 18 in your playground snippet).

Unrelated, but here is a simpler version of ReplayFileExists:
```
func FileIsReadable(file string) bool {
	_, err := os.Stat(file)
	return err == nil
}
```
While Stat may return other errors that don't necessarily mean the file doesn't exist, any error suggests that there will be a problem reading the file.
